### ISSUE TITLE
Add paramters from OwinContext?

### ISSUE THREAD

**Issue by abergs** [marcinbudny/applicationinsights-owinextensions#15]
How would I go about adding custom properties from the owin context?

For example I have a  middleware that sets some user information in the OWIN context and I would like to have a initializer/processor add these to all the telemetry.

**Comment by marcinbudny** [comment]
Hi Anders,

See [here](https://github.com/marcinbudny/applicationinsights-owinextensions#adding-custom-properties-to-telemetry) You should be able to get to the `IOwinContext` via either request or response passed to the `getContextProperties` func.

**Comment by abergs** [comment]
I see. Will see if I can get it to work and maybe improve the docs at the same time! :)

**Comment by marcinbudny** [comment]
Looking back at this functionality, it would make more sense to pass the `IOwinContext` to the `getContextProperties` since both request and response could be extracted from there. And at the same time it would be a more general solution. If you have some time, please drop me a PR for that (but we have to keep backwards compatibility).

**Comment by marcinbudny** [comment]
I hope the question is now answered. Closing the issue.
