### ISSUE TITLE
Add correlation ID to headers

### ISSUE THREAD

**Issue by aarondandy** [marcinbudny/applicationinsights-owinextensions#4]
When integrating with other parts of our systems we would rather just propagate correlation ID through the header instead of using `OperationIdContext.Get()` in multiple places withon our code. It would be pretty neat if I could toggle on an option to enable the correlation ID header to be added if not found based on the value in `OperationIdContext.Get()`.

Currently I work around this by just adding another middleware:

```csharp
appBuilder.Use((IOwinContext owinContext, Func<Task> next) =>
{
    if (!owinContext.Request.Headers.ContainsKey(HttpHeaders.CorrelationId))
    {
        owinContext.Request.Headers[HttpHeaders.CorrelationId] = OperationIdContext.Get();
    }

    return next();
});
```

but I think it would be way more convenient if I could just configure the `OperationIdContextMiddlewareConfiguration` instance with a property like `ShouldWriteHeader = true` .

**Comment by marcinbudny** [comment]
Hi Aaron,
I don't think I understand the reason why you need to modify headers on the incoming request. Is the correlation id somehow automatically propagated to other services in your solution? How is getting the value from header different from getting it from `OperationIdContext.Get()`?

**Comment by jsquire** [comment]
Hi Marc,

If one of our services receives a correlation identifier as part of the request headers, we honor it.  If not, a new correlation id is generated.  In order to ensure that we have a single and consistent place to read the correlation id from, if we need to generate the identifier, we inject a header with it into the request as if it was provided by a caller.

If you're curious as to the reasoning behind this, our goal is to ensure that we have a consistent correlation id as we chain calls through the different dependent services in our stack.  This gives us the ability to better tie together log and telemetry data between the services and build one logical view of all activity tied to a specific request regardless of how many different service boundaries it crosses while being fulfilled.

**Comment by aarondandy** [comment]
Another consideration in addition to what @jsquire mentioned is that when writing code and tests it is a lot easier for us to deal with the headers collection than it is to test around the static method `OperationIdContext.Get` . This also lets us just keep that operation ID concern isolated to the headers and also ensures we always have one there that matches the HTTP request operation ID. We use this same operation ID all over our code and in other systems that do not use HTTP.

**Comment by marcinbudny** [comment]
@jsquire The library actually already supports this, however the "single and consistent place to read the correlation id from" is not a header, but rather the `OperationIdContext.Get()`. Take a look here:
https://github.com/marcinbudny/applicationinsights-owinextensions/blob/develop/src/ApplicationInsights.OwinExtensions/OperationIdContextMiddleware.cs#L46

@aarondandy If static method is a problem in a test, the value can also be extracted from OWIN env dictionary using the `ApplicationInsights.OwinExtensions.OperationIdContext` key. I mean integration tests here. For unit testing you should probably put some layer of abstraction over it anyway, something like `IOperationIdProvider` you could substitute in the test.

Modifying incoming headers seems a bit of a workaround solution.

**Comment by aarondandy** [comment]
Okay.
